import type { Course } from "../../domain/entities/course";
import type { CourseCatalogRepository } from "../../domain/repositories/CourseCatalogRepository";

const COURSES: Course[] = [
  {
    id: "MAT101",
    name: "Matemática Básica",
    code: "MAT101",
    credits: 4,
    cycle: 1,
    prerequisites: [],
    status: "approved",
    isInStudyPlan: true,
  },
  {
    id: "COM101",
    name: "Comunicación Efectiva",
    code: "COM101",
    credits: 3,
    cycle: 1,
    prerequisites: [],
    status: "approved",
    isInStudyPlan: true,
  },
  {
    id: "FIS101",
    name: "Física General",
    code: "FIS101",
    credits: 4,
    cycle: 1,
    prerequisites: [],
    status: "approved",
  },
  {
    id: "PROG101",
    name: "Introducción a la Programación",
    code: "PROG101",
    credits: 4,
    cycle: 1,
    prerequisites: [],
    status: "approved",
  },
  {
    id: "CAL101",
    name: "Cálculo Diferencial",
    code: "CAL101",
    credits: 4,
    cycle: 2,
    prerequisites: ["MAT101"],
    status: "approved",
  },
  {
    id: "ALG101",
    name: "Álgebra Lineal",
    code: "ALG101",
    credits: 4,
    cycle: 2,
    prerequisites: ["MAT101"],
    status: "approved",
  },
  {
    id: "PROG102",
    name: "Programación Orientada a Objetos",
    code: "PROG102",
    credits: 4,
    cycle: 2,
    prerequisites: ["PROG101"],
    status: "approved",
  },
  {
    id: "CAL201",
    name: "Cálculo Integral",
    code: "CAL201",
    credits: 4,
    cycle: 3,
    prerequisites: ["CAL101"],
    status: "approved",
  },
  {
    id: "EDD101",
    name: "Estructuras de Datos",
    code: "EDD101",
    credits: 4,
    cycle: 3,
    prerequisites: ["PROG102"],
    status: "approved",
  },
  {
    id: "ARQ101",
    name: "Arquitectura de Computadoras",
    code: "ARQ101",
    credits: 4,
    cycle: 3,
    prerequisites: ["PROG102"],
    status: "approved",
  },
  {
    id: "EST101",
    name: "Estadística General",
    code: "EST101",
    credits: 4,
    cycle: 4,
    prerequisites: ["CAL101"],
    status: "approved",
  },
  {
    id: "BD101",
    name: "Bases de Datos",
    code: "BD101",
    credits: 4,
    cycle: 4,
    prerequisites: ["EDD101"],
    status: "approved",
  },
  {
    id: "RED101",
    name: "Redes de Computadoras",
    code: "RED101",
    credits: 4,
    cycle: 4,
    prerequisites: ["ARQ101"],
    status: "approved",
  },
  {
    id: "ALG201",
    name: "Algoritmos y Complejidad",
    code: "ALG201",
    credits: 4,
    cycle: 5,
    prerequisites: ["EDD101", "CAL201"],
    status: "failed",
  },
  {
    id: "SIS101",
    name: "Sistemas Operativos",
    code: "SIS101",
    credits: 4,
    cycle: 5,
    prerequisites: ["ARQ101", "EDD101"],
    status: "not_taken",
  },
  {
    id: "ING101",
    name: "Ingeniería de Software I",
    code: "ING101",
    credits: 4,
    cycle: 5,
    prerequisites: ["PROG102", "BD101"],
    status: "not_taken",
  },
  {
    id: "IA101",
    name: "Inteligencia Artificial",
    code: "IA101",
    credits: 4,
    cycle: 6,
    prerequisites: ["ALG201", "EST101"],
    status: "not_taken",
  },
  {
    id: "WEB101",
    name: "Desarrollo Web Avanzado",
    code: "WEB101",
    credits: 4,
    cycle: 6,
    prerequisites: ["ING101"],
    status: "not_taken",
  },
  {
    id: "SEG101",
    name: "Seguridad Informática",
    code: "SEG101",
    credits: 4,
    cycle: 6,
    prerequisites: ["RED101", "SIS101"],
    status: "not_taken",
  },
  {
    id: "PROY101",
    name: "Proyecto de Software",
    code: "PROY101",
    credits: 6,
    cycle: 7,
    prerequisites: ["ING101", "WEB101"],
    status: "not_taken",
  },
  {
    id: "CLOUD101",
    name: "Computación en la Nube",
    code: "CLOUD101",
    credits: 4,
    cycle: 7,
    prerequisites: ["SIS101", "RED101"],
    status: "not_taken",
  },
  {
    id: "ETI101",
    name: "Ética y Legislación en TI",
    code: "ETI101",
    credits: 3,
    cycle: 8,
    prerequisites: [],
    status: "not_taken",
  },
  {
    id: "PRAC101",
    name: "Prácticas Pre-Profesionales",
    code: "PRAC101",
    credits: 6,
    cycle: 8,
    prerequisites: ["PROY101"],
    status: "not_taken",
  },
  {
    id: "ELECT101",
    name: "Electivo Profesional",
    code: "ELECT101",
    credits: 4,
    cycle: 8,
    prerequisites: [],
    status: "not_taken",
  },
];

export const createStaticCourseCatalogRepository = (): CourseCatalogRepository => {
  const listCourses: CourseCatalogRepository["listCourses"] = async () =>
    COURSES.map((course) => ({
      ...course,
      prerequisites: [...course.prerequisites],
    }));

  return {
    listCourses,
  };
};
